### ISSUE TITLE
evap should probably have protected branches turned on

### ISSUE THREAD

**Issue by gerring** [eclipse/eavp#1]
1. Matt Ward will give us temporary admin
2. Under settings turn on protected branches to avoid force push
3. Can optionally force all pushes to p[ass build/test (recommended)

**Comment by jayjaybillings** [comment]
Why?

From my phone.
________________________________
From: Matthew Gerring
Sent: Saturday, March 12, 2016 5:43 AM
To: eclipse/eavp
Subject: [eavp] evap should probably have protected branches turned on (#1)



  1.  Matt Ward will give us temporary admin
  2.  Under settings turn on protected branches to avoid force push
  3.  Can optionally force all pushes to p[ass build/test (recommended)

-

**Comment by jayjaybillings** [comment]
@gerring Why?

**Comment by gerring** [comment]
Stops a forced push and optionally use it to enforce a passing build before
checking for everyone. I recommend this for collaborative projects.

**Comment by jayjaybillings** [comment]
How does it work to make sure all pushes pass the build and test? I admit I don't care about this for the force push reason, but if I can turn it on to enforce builds before checkin, I'm all for it.

Can you attach a screenshot or something showing what it looks like and tell us how it works for that purpose please?
