### ISSUE TITLE
Target has the wrong Nebula update site

### ISSUE THREAD

**Issue by SmithRWORNL** [eclipse/eavp#117]
The target has http://download.eclipse.org/technology/nebula/archives/Q32014/release , which is no longer a valid update site. The target needs to be updated to point to the new location. 

I'm moving this bug to our current issue tracker from https://bugs.eclipse.org/bugs/show_bug.cgi?id=498919

**Comment by jayjaybillings** [comment]
I committed my modified target the other day. Sorry, I forgot! It is in jay/model. Please check it out and see if it works for you:

https://github.com/eclipse/eavp/blob/jay/model/org.eclipse.eavp.target.neon/eavp.test.target

**Comment by SmithRWORNL** [comment]
I tested the new target and the build worked fine for me.

**Comment by SmithRWORNL** [comment]
As you suggested, I retried the build with the target renamed to neon.target and setting it as the target platform. This time I got the following error:

[ERROR] Cannot resolve project dependencies:
[ERROR]   You requested to install 'org.eclipse.sdk.feature.group 0.0.0' but it could not be found

**Comment by SmithRWORNL** [comment]
Addressed by commit 5b7bb37385686f341fc36b1b395d487b6e1b3cc1.

**Comment by jayjaybillings** [comment]
I don't believe you. That commit doesn't have any pom or target files in it! ;-)

https://github.com/eclipse/eavp/commit/5b7bb37385686f341fc36b1b395d487b6e1b3cc1

**Comment by SmithRWORNL** [comment]
Technically, it was 7b7b077483e128774f2c2e510e27bc36fdfc3ec6 that changed the files and 5b7bb37385686f341fc36b1b395d487b6e1b3cc1 that merged the changes into next.
