### ISSUE TITLE
Why does EAVP have two entirely different select series boxes for simple plots?

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/eavp#136]
Why does EAVP have two entirely different select series boxes/mechanisms on simple/csv plots? One you get by clicking "Select Series" in the upper left and the other you get by right clicking and selecting "Select Series." They should be identical in the absence of a better reason!

![screenshot from 2016-12-12 11-45-05](https://cloud.githubusercontent.com/assets/6378849/21107693/972b535e-c060-11e6-8583-e39b84645cd6.png)
![screenshot from 2016-12-12 11-45-16](https://cloud.githubusercontent.com/assets/6378849/21107694/97324dbc-c060-11e6-9b4f-f03602947a33.png)

**Comment by SmithRWORNL** [comment]
As of commit 86cbef484349048cb83b9d32de61d7ca249b7fd5 the Select Series... button now sets up the dialog the same way as the other one.
