### ISSUE TITLE
Build error, "Cannot resolve project dependencies"

### ISSUE THREAD

**Issue by kburova** [eclipse/eavp#14]
I installed new ice, from http://download.eclipse.org/ice/builds/next/ , cloned from github(next branch) and imported all the projects, i ran EAVP.launch, and got an error in the end of build:

-----------------------

[INFO] Scanning for projects...
[INFO] Computing target platform for MavenProject: org.eclipse.ice:org.eclipse.eavp.viz:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz/pom.xml
[INFO] Adding repository http://download.eclipse.org/ease/update/nightly
[INFO] Fetching p2.index from http://download.eclipse.org/releases/mars/ (0B at 0B/s)
[INFO] Adding repository http://download.eclipse.org/releases/mars
[INFO] Fetching p2.index from http://download.eclipse.org/technology/epp/packages/mars/ (0B at 0B/s)
[INFO] Fetching p2.index from http://download.eclipse.org/releases/mars/201506241002/ (0B at 0B/s)
[INFO] Fetching p2.index from http://download.eclipse.org/releases/mars/201510021000/ (0B at 0B/s)
[INFO] Fetching p2.index from http://download.eclipse.org/releases/mars/201602261000/ (0B at 0B/s)
[INFO] Fetching p2.index from http://download.eclipse.org/tools/orbit/downloads/drops/R20140525021250/repository/ (0B at 0B/s)
[INFO] Adding repository http://download.eclipse.org/tools/orbit/downloads/drops/R20140525021250/repository
[INFO] Adding repository http://download.eclipse.org/technology/nebula/archives/Q32014/release
[INFO] Adding repository http://download.eclipse.org/nattable/releases/1.3.0/repository
[INFO] Adding repository http://download.eclipse.org/technology/swtbot/releases/latest
[INFO] Adding repository http://eclipseice.ornl.gov/downloads/visit_java_client/1.0.0-SNAPSHOT/p2
[INFO] Adding repository http://eclipseice.ornl.gov/downloads/spotify_docker_client/SNAPSHOT-3.1.1-SHADED/p2
[INFO] Resolving dependencies of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz/pom.xml
[INFO] Resolving class path of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz/pom.xml
[INFO] Computing target platform for MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service/pom.xml
[INFO] Resolving dependencies of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service/pom.xml
[INFO] Resolving class path of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service/pom.xml
[INFO] Computing target platform for MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.geometry:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.geometry/pom.xml
[INFO] Resolving dependencies of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.geometry:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.geometry/pom.xml
[INFO] Resolving class path of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.geometry:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.geometry/pom.xml
[INFO] Computing target platform for MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.geometry.test:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.geometry.test/pom.xml
[INFO] Resolving dependencies of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.geometry.test:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.geometry.test/pom.xml
[INFO] Resolving class path of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.geometry.test:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.geometry.test/pom.xml
[INFO] Computing target platform for MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.javafx:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.javafx/pom.xml
[INFO] Resolving dependencies of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.javafx:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.javafx/pom.xml
[INFO] Resolving class path of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.javafx:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.javafx/pom.xml
[INFO] Computing target platform for MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.javafx.geometry:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.javafx.geometry/pom.xml
[INFO] Resolving dependencies of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.javafx.geometry:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.javafx.geometry/pom.xml
[INFO] Resolving class path of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.javafx.geometry:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.javafx.geometry/pom.xml
[INFO] Computing target platform for MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.javafx.geometry.test:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.javafx.geometry.test/pom.xml
[INFO] Resolving dependencies of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.javafx.geometry.test:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.javafx.geometry.test/pom.xml
[INFO] Resolving class path of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.javafx.geometry.test:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.javafx.geometry.test/pom.xml
[INFO] Computing target platform for MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.javafx.mesh:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.javafx.mesh/pom.xml
[INFO] Resolving dependencies of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.javafx.mesh:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.javafx.mesh/pom.xml
[INFO] Resolving class path of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.javafx.mesh:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.javafx.mesh/pom.xml
[INFO] Computing target platform for MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.javafx.test:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.javafx.test/pom.xml
[INFO] Resolving dependencies of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.javafx.test:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.javafx.test/pom.xml
[INFO] Resolving class path of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.javafx.test:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.javafx.test/pom.xml
[INFO] Computing target platform for MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.mesh:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.mesh/pom.xml
[INFO] Resolving dependencies of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.mesh:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.mesh/pom.xml
[INFO] Resolving class path of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.mesh:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.mesh/pom.xml
[INFO] Computing target platform for MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.mesh.test:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.mesh.test/pom.xml
[INFO] Resolving dependencies of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.mesh.test:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.mesh.test/pom.xml
[INFO] Resolving class path of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.mesh.test:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.mesh.test/pom.xml
[INFO] Computing target platform for MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.paraview:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.paraview/pom.xml
[INFO] Resolving dependencies of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.paraview:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.paraview/pom.xml
[INFO] Resolving class path of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.paraview:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.paraview/pom.xml
[INFO] Computing target platform for MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.paraview.test:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.paraview.test/pom.xml
[INFO] Resolving dependencies of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.paraview.test:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.paraview.test/pom.xml
[INFO] Resolving class path of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.paraview.test:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.paraview.test/pom.xml
[INFO] Computing target platform for MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.paraview.web:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.paraview.web/pom.xml
[INFO] Resolving dependencies of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.paraview.web:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.paraview.web/pom.xml
[INFO] Resolving class path of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.paraview.web:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.paraview.web/pom.xml
[INFO] Computing target platform for MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.test:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.test/pom.xml
[INFO] Resolving dependencies of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.test:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.test/pom.xml
[INFO] Resolving class path of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.test:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.test/pom.xml
[INFO] Computing target platform for MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.visit:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.visit/pom.xml
[INFO] Resolving dependencies of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.visit:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.visit/pom.xml
[INFO] Resolving class path of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.visit:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.visit/pom.xml
[INFO] Computing target platform for MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.visit.test:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.visit.test/pom.xml
[INFO] Resolving dependencies of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.visit.test:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.visit.test/pom.xml
[INFO] Resolving class path of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.service.visit.test:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.service.visit.test/pom.xml
[INFO] Computing target platform for MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.test:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.test/pom.xml
[INFO] Resolving dependencies of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.test:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.test/pom.xml
[INFO] Resolving class path of MavenProject: org.eclipse.ice:org.eclipse.eavp.viz.test:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.viz.test/pom.xml
[INFO] Computing target platform for MavenProject: org.eclipse.eavp:org.eclipse.eavp.feature:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.feature/pom.xml
[INFO] Resolving dependencies of MavenProject: org.eclipse.eavp:org.eclipse.eavp.feature:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.feature/pom.xml
[INFO] Resolving class path of MavenProject: org.eclipse.eavp:org.eclipse.eavp.feature:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.feature/pom.xml
[INFO] Computing target platform for MavenProject: org.eclipse.ice:org.eclipse.ice.repository:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.repository/pom.xml
[INFO] Resolving dependencies of MavenProject: org.eclipse.ice:org.eclipse.ice.repository:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.repository/pom.xml
[INFO] {osgi.os=linux, osgi.ws=gtk, org.eclipse.update.install.features=true, osgi.arch=x86}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.eclipse.ice.repository raw:2.1.8.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):2.1.8-SNAPSHOT
[ERROR]   Missing requirement: org.eclipse.ice.repository raw:2.1.8.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):2.1.8-SNAPSHOT requires 'org.eclipse.eavp.feature.feature.group [2.1.8.20160208]' but it could not be found
[ERROR] 
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: org.eclipse.ice:org.eclipse.ice.repository:2.1.8-SNAPSHOT @ /Users/apple/git/ice/org.eclipse.eavp.repository/pom.xml: See log for details -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException

----------------------------------------

**Comment by jayjaybillings** [comment]
Robert will take a look at this with you. Thanks for submitting.

**Comment by SmithRWORNL** [comment]
This bug is not present in EAVP itself. It was resolved in EAVP by commit bae5d247b12c26a26cb6f2ad6eca4a05668bfa25, but is still extant in the copies of the EAVP packages present in the ICE repo.

I'm going to close this bug and reopen the one filled for ICE.
