### ISSUE TITLE
Split packages in org.eclipse.eavp.datastructures

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/eavp#145]
We recently split org.eclipse.eavp.datastructures into two bundles, one of which is a UI bundle. The UI bundle needs to have its main package name changed to match its bundle name so that we do not have split packages. This is causing build failures in ICE.

**Comment by SmithRWORNL** [comment]
Already fixed by commit ef0d2b71e773bacbc29dcb1bde804380c4dee672. Rather, I'd forgotten to commit the corresponding changes in ICE for the new package name.
