### ISSUE TITLE
ParaView service is not compatible with ParaView versions above 5.2

### ISSUE THREAD

**Issue by SmithRWORNL** [eclipse/eavp#146]
The ParaView service will hang without launching when on a Fedora machine, but not on other Linux installs such as CentOS.

**Comment by SmithRWORNL** [comment]
This seems to be caused by Fedora 25 not having the PYTHONPATH set correctly when pvpython is run. For now, it can be fixed by manually adding necessary paths to the PYTHONPATH (run pvpython http_pvw_server.py to get an error message for what import is failing, then do pip install to get the path to where it is installed, and repeat until the script runs.)

We need to add this to the documentation and/or fix our script so that it can always find the correct modules.

**Comment by SmithRWORNL** [comment]
It seems the real issue wasn't the operating system (which was a coincidence), but that ParaView 5.3 has removed some scripts (wamp.py and protocols.py) that are necessary to run the server script. We need to investigate a new version of the script that is compatible with the new ParaView version. 

Currently, ParaView 5.2 is the last working version.

**Comment by jayjaybillings** [comment]
You should probably contact Kitware...


Jay


Jay Jay Billings
Team Lead, Scientific Software Development
Oak Ridge National Laboratory
Twitter Handle: @jayjaybillings
________________________________

**Comment by SmithRWORNL** [comment]
This was resolved when Kitware re-added these scripts to their 5.3 version releases.
