### ISSUE TITLE
Spotify Docker Client in Build

### ISSUE THREAD

**Issue by amccaskey** [eclipse/eavp#15]
Just pulled down EAVP next and ran the build. I noticed it added the eclipseice.ornl.gov spotify-docker-client-shaded p2 site. Is this really necessary for EAVP?

**Comment by amccaskey** [comment]
If it's not needed we should remove it from the target.

**Comment by SmithRWORNL** [comment]
I replaced the EAVP target with the full ICE one, because some things were missing from it. Commit 7b5c9ff8be8392749bbb23a93ac1adb5af3538cb has pared it back down to the correct size.
