### ISSUE TITLE
When creating a plot with CSVVizService URI is not validated properly

### ISSUE THREAD

**Issue by anarak** [eclipse/eavp#150]
The null pointer exception is thrown #149 because the current implementation doesn't validate the file path specified in URI in `createPlot` properly. There are some validations that check if URI is null or that check the extension of a file but not the existence of a file at the specified directory. 

It seems that independent series returned by `getIndependentSeries` in `CSVProxyPlot` are still null and that's where execution halts and it still works, however, debugging lets executing the rest of code successfully and it seems that independent series get reassigned later. I think this may be a thread issue.

**Comment by SmithRWORNL** [comment]
The old CSVVizService will be replaced in 0.3
