### ISSUE TITLE
Need zoom and "reset view" buttons for VisIt plots

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/eavp#20]
I was showing VisIt to a colleague and I tried to zoom in with my mousepad on my Dell XPS 15, which does not have a scroll wheel, but a multitouch mouse pad.

I tried to zoom in and it immediately hung up while it re-rendered to a very, very small size. I tried to zoom out and it just zoomed in to a single pixel, after hanging for another minute or so. I was trapped in this view and couldn't get out of it, even when I closed and reopened the plot.

If I use my USB mouse with a wheel, it works fine, although it is a little slow.

We need buttons that will
1.) Reset the view to the original state
2.) Zoom in
3.) Zoom out

**Comment by jayjaybillings** [comment]
Please note that these buttons should go in the toolbar at the top of the plot, not in the VisIt view or the bottom toolbar.

The should be stylized to look good. I don't want buttons that say "Zoom In," "Zoom Out," and "Reset." So please make sure that they have standard images +,- for zoom and something appropriate for reset. The text descriptors should go in as tooltips.

**Comment by SmithRWORNL** [comment]
Buttons added by commit 047c72ef7883454949ec2b98479ab66b02412e38.

I'm leaving this issue open as the problem with zooming with a multitouch mousepad remains unresolved.

**Comment by jayjaybillings** [comment]
Are these issues still unresolved?

**Comment by SmithRWORNL** [comment]
I originally wasn't able to try to reproduce the multi-touch mouse pad issue. Now that I have the Mac laptop, I can try it out and see if I can fix it.

**Comment by SmithRWORNL** [comment]
VisIt will no longer be supported in 0.3, so the multi-touch mouse pad issue will not be fixed.
