### ISSUE TITLE
VisIt plot editor plays backwards instead of skipping to first slide

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/eavp#21]
The VisIt plot editor will play backwards instead of stopping and skipping to a previous slide when selected. I just played the wave example to the middle of its run, stopped it and then clicked the first slide and it played backwards. 

You can also turn off the loop so that it stops at the end and in the hidden frame rate menu use the "first step" button to return to the beginning. It will then play through the entire visualization backwards.

Obviously, it should just skip to the selected slide instead of rendering backwards.

**Comment by SmithRWORNL** [comment]
Fixed by commit 36073f0d33483e85c166206c9acd37e4fffbf35f.
