### ISSUE TITLE
VisIt plots render exceptionally slow under rotation

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/eavp#23]
When I am rotating a VisIt plot on my Fedora 23 box, it renders really slow. This could in part be due to the drivers, I suppose, but I think it is more likely that there is some underlying issue.

It would be good to talk to Hari and see if we can figure out how to send image diffs instead of whole images too. That might alleviate most of this.

**Comment by SmithRWORNL** [comment]
VisIt will no longer be supported in 0.3.
