### ISSUE TITLE
VisIt preferences page sometimes fails to save input

### ISSUE THREAD

**Issue by SmithRWORNL** [eclipse/eavp#26]
When the VisIt preferences page is opened with a connection already in the table, edits to the connection may not be applied or saved when "Apply" or "Ok" is pressed. 

A work around for this issue is to delete all rows from the table, press "Ok", reopen the preferences page, and make a new connection.

**Comment by SmithRWORNL** [comment]
I can no longer reproduce this bug as of the latest unstable nightly, so I'm marking it as closed. It's either been fixed, or else I was trying to apply changes before removing focus from the line I was editing, meaning that the Entry hadn't been saved so there were no actual changes to apply.

**Comment by kburova** [comment]
I launched ICE today, started new workspace, went to ICE -> Preferences -> Visualization ->VisIt. Added valid path  (/Users/apple/Desktop/VisIt/bin) for connection and it gave me and error message, i tried 3 more times and got errors again. After that it stopped giving me error messages at all. I tried to relaunch it in a same workspace, still had no response. And then I added a wrong path in purpose, it ignored it any way. So in my  understanding changes do not get applied after pressing 'apply' and 'ok'. So it feels like this bug needs to be re-opened.

**Comment by jayjaybillings** [comment]
Reopened. Talk to @SmithRWORNL.

**Comment by SmithRWORNL** [comment]
@kburova 
When this happens, when you close the preferences menu and reopen it, are the changes you made saved?

**Comment by SmithRWORNL** [comment]
Partially, this is being caused by incorrect error messages. ICE is throwing up a dialog saying the connection failed when it's actually connecting. You can, for example, open an ICE file with VisIt even after getting the error. 

The other half of this issue is that the Preferences menu UI isn't user friendly enough. Both Ksenia and I have repeatedly made a change to a table row, then tried to hit "Apply" or "Ok" before hitting enter, assumed that our change was being ignored, and filed bugs about it. However, what's actually happening is that we haven't finished editing the table row, because that text cell still has focus, meaning that the entry hasn't had its old value overwritten yet, and so the Preferences menu doesn't recognize that any changes have taken place. We may want to talk about giving the user better indication that they haven't finished editing the table, or else have the buttons automatically save what they have in the text field before attempting to apply/save the table.

**Comment by jayjaybillings** [comment]
We actually need to talk about completely redoing that whole preferences menu. It's terrible.

**Comment by SmithRWORNL** [comment]
VisIt will no longer be supported in 0.3
