### ISSUE TITLE
Need to test Paraview support

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/eavp#27]
We need to retest our Paraview support. Here is a document that Jordan wrote showing how to connect to it.

[ParaViewWiki.docx](https://github.com/eclipse/eavp/files/192762/ParaViewWiki.docx)

**Comment by SmithRWORNL** [comment]
Currently, ParaView is working for Linux and Mac.

I was able to install ParaView, launch the server, and connect to it on ICE using CentOS and Mac. 

On Fedora 22, I ran into issues trying to get it to work. I was able to partially resolve this by deleting some of the files from the ParaView installation's packaged libraries, causing it to use the operating system's versions of those files instead. I was still stuck with driver issues that prevent the machine from launching ParaView. (The driver problems aren't specific to our server script. I can't use ParaView at all on my Fedora machine.)

We don't currently support remote ParaView connections and, according to the documentation, the ParaView service isn't working on Windows, meaning that we have no support for ParaView on that OS.
