### ISSUE TITLE
Preferences-> VisIt : Correct path marked as a wrong one

### ISSUE THREAD

**Issue by kburova** [eclipse/eavp#34]
Testing bug #26,  I realized that when I provide a correct path for Visit connection via **Preferences->Visualization->Visit** i get a message that connection fails. I tested this path by launching Visit in Visualization Perspective and it worked.

**Comment by kburova** [comment]
So update for this bug: I reinstalled ICE, from unstable-nightly(latest), i connected via Preferences and it worked. Then i changed path to wrong one, got error message, changed back to right one and it failed with new port or/and name (not only for an error message, couldn't open Visit file). Then i changed attributes again in a few secs and it worked, but still gave me an error message. So finalizing, connection works but it's inconsistent.

**Comment by SmithRWORNL** [comment]
Commit 3bd8eeb5af03d073355f18bb2ef7609db822b0ee stops these incorrect error dialogs from opening.
