### ISSUE TITLE
VisIt Port not being cleared after closing connection

### ISSUE THREAD

**Issue by amccaskey** [eclipse/eavp#36]
Create a new VisIt connection successfully. Then delete it from the preferences and click Apply. This successfully removes the VisIt connection. Now try to create a new VisIt connection with the same port. This is failing to create a connection for me. Here's the output 

Apr 14, 2016 3:46:55 PM gov.lbnl.visit.swt.VisItSwtConnection$VisItReaderThread run
INFO: >> Running: viewer2.9.2 -nowin -noint -shared_port 9600 -shared_password notused -interactions -sleepmode -host 127.0.0.1 -port 5600
Apr 14, 2016 3:46:55 PM gov.lbnl.visit.swt.VisItSwtConnection$VisItReaderThread run
INFO: >> QObject::connect: Cannot connect (null)::destroyed() to QHostInfoLookupManager::waitForThreadPoolDone()
Apr 14, 2016 3:46:56 PM gov.lbnl.visit.swt.VisItSwtConnection$VisItReaderThread run
INFO: >> WARNING: Failed to start listening server on port: 9600
15:46:56.934 [pool-8-thread-1] DEBUG o.e.e.v.s.connections.VizConnection - org.eclipse.eavp.viz.service.visit.connections.VisItConnection message: Notifying listeners of a connection state change to "Failed" with the message "The connection failed to connect.".
15:46:56.934 [pool-8-thread-1] DEBUG o.e.e.v.s.connections.VizConnection - org.eclipse.eavp.viz.service.visit.connections.VisItConnection message: No listeners to notify.
Apr 14, 2016 3:46:56 PM gov.lbnl.visit.swt.VisItSwtConnection$VisItReaderThread run
SEVERE: Failed to listen
java.io.IOException: Failed to listen
	at gov.lbnl.visit.swt.VisItSwtConnection$VisItReaderThread.run(VisItSwtConnection.java:937)
	at java.lang.Thread.run(Thread.java:745)

**Comment by SmithRWORNL** [comment]
Fixed by 6b54dc8cc224446169dbf8e272af1b5c7a2f7327.
