### ISSUE TITLE
The org.eclipse.eavp.viz.modeling pom.xml has incorrect artifactId

### ISSUE THREAD

**Issue by jarrah42** [eclipse/eavp#4]
The artifactId is org.eclipse.eavp.viz.service instead of org.eclipse.eavp.viz.modeling

**Comment by SmithRWORNL** [comment]
There are a couple of other mistakes of this kind (ie org.eclipse.eavp.viz.service.datastructures.test instead of org.eclipse.eavp.viz.datastructures in the manifest). I've corrected them in my local branch and they'll be pushed into next when I get the build running.

**Comment by jarrah42** [comment]
I have the build working in my fork if you'd like me to create a pull request.

**Comment by SmithRWORNL** [comment]
@jarrah42 
Yes, that would be great. Thanks!

**Comment by jarrah42** [comment]
you should probably accept the current pull request first, otherwise there will be a lot of unrelated changes

**Comment by jarrah42** [comment]
i just saw you did this already, thanks.

**Comment by jarrah42** [comment]
Done.
