### ISSUE TITLE
Need better name for IVizService.getFactory

### ISSUE THREAD

**Issue by amccaskey** [eclipse/eavp#47]
What factory? 

https://github.com/eclipse/eavp/blob/ef49a6e551f060a40baf9ff3b2a6effc2d5c6dcb/org.eclipse.eavp.viz.service/src/org/eclipse/eavp/viz/service/IVizService.java#L68

We should name this something more specific like getControllerProviderFactory.

**Comment by SmithRWORNL** [comment]
Addressed by commit 5fa27ff2edefab5cdc97d21c01c313fcc5a8d8b5.
