### ISSUE TITLE
Commit messages should be sent to the mailing list

### ISSUE THREAD

**Issue by SmithRWORNL** [eclipse/eavp#48]
When a developer commits to any of EAVP's branches, the commit message and list of edited paths should be forwarded to the mailing list at eavp-dev (at) eclipse (dot) org.

**Comment by jayjaybillings** [comment]
I don't know if @eclipsewebmaster gets emails about these bugs. So, if you don't hear back in a few days, please let me know.

**Comment by eclipsewebmaster** [comment]
I've added the email service and pointed it at eavp-dev at eclipse dot org, so mail should start to show up.

**Comment by SmithRWORNL** [comment]
I'm now getting emails from commits I put in, so this issue is resolved. Thanks!
