### ISSUE TITLE
Need a separate model for new EMF-based rendering classes

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/eavp#59]
@SmithRWORNL, please move your recent additions to a separate EMF model. Namely, the following classes should be in a separate bundle called org.eclipse.eavp.geometry.view.model:

MeshCache<T>
RenderObject<T>
RenderObjectDecorator<T>
TextureDecorator
OpacityDecorator
WireframeDecorator
ColorDecorator
IRenderElement<T>

This new model can reference the org.eclipse.january.geometry.model but should be in the January bundle. That bundle should only contain data and I/O structures and will soon be moved to January.

**Comment by SmithRWORNL** [comment]
Fixed by commit 77af9ec089e180d2badd5d45ef57304f4a1cb4e5.
