### ISSUE TITLE
Replace instances of "crap" with "bad stuff" in CSVPlot

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/eavp#66]
The IP team has finished reviewing our initial contribution. They have requested that we clean up instances of the work "crap" in CSVPlot. Please change it to "bad stuff" instead.

CSVPlot is at org.eclipse.eavp.viz.service/src/org/eclipse/eavp/viz/service/csv/CSVPlot.java

**Comment by SmithRWORNL** [comment]
Fixed by commit 1e66d9ac455af493b2c40d4e09e3a19479c29414
