### ISSUE TITLE
STL importer needs implementation in geometry model

### ISSUE THREAD

**Issue by KasperGam** [eclipse/eavp#67]
The STL importer, ASCIISTLImpoter needs implementation in the new geometry model for both ASCII and Binary STL files.

**Comment by jayjaybillings** [comment]
Just accepted #68 to address this. @SmithRWORNL please check this.

**Comment by jayjaybillings** [comment]
I meant to say that #69 addresses this. Kasper's title was bad. ;-)

**Comment by SmithRWORNL** [comment]
This has been merged into next as of commit 0b1bbd9317bfeddbd5373b6df195473e0c4525e0
