### ISSUE TITLE
STLGeometryImporter needs test code

### ISSUE THREAD

**Issue by SmithRWORNL** [eclipse/eavp#70]
The STLGeometryImporterTest class in org.eclipse.january.geometry needs to be implemented. The testLoad_Path() function should include test cases of the STLGeometryImporter importing various file types (binary, non-binary, invalid file path, malformed file, etc.)  and checking that the resulting data is valid.

**Comment by KasperGam** [comment]
Yes I, I have been posting everything to the github repo on my account: KasperGam/IGESImport
|   |
|   |  |   |   |   |   |   |
| KasperGam/IGESImportIGESImport - Xtext project for importing IGES geometry files |
|  |
| View on github.com | Preview by Yahoo |
|  |
|   |


 
Can't wait to talk about it when I get back!
   

 On Friday, July 1, 2016 2:35 PM, SmithRWORNL <notifications@github.com> wrote:
 

 The STLGeometryImporterTest class in org.eclipse.january.geometry needs to be implemented. The testLoad_Path() function should include test cases of the STLGeometryImporter importing various file types (binary, non-binary, invalid file path, malformed file, etc.) and checking that the resulting data is valid. —

**Comment by SmithRWORNL** [comment]
I thought I remembered that from the demo yesterday. This can be one of the issues you reference when you make your next pull request. Good work!

**Comment by SmithRWORNL** [comment]
Addressed by pull request #71
