### ISSUE TITLE
January bundles in jay/model are missing files

### ISSUE THREAD

**Issue by jayjaybillings** [eclipse/eavp#75]
The January bundles in jay/model are missing files such as about.html and license.html. Please make sure that all of these bundles in this branch have these files.

This is just because most of them are brand new and autogenerated.

**Comment by SmithRWORNL** [comment]
Commit e1fb53f6a3295cc955df70189073686e7eb76c59 includes about.html and license.html in all bundles. Following Jonah Graham's example, I've also included them in the build.properties files.
