### ISSUE TITLE
There are problems with the january.geometry.model bundle, and the STLGeometryImporter fails tests

### ISSUE THREAD

**Issue by KasperGam** [eclipse/eavp#79]
The bundle's manifest declares a different name for it's bundle now, breaking the editor bundle's code. It does not have the right name for the new EMF model in the plugin.xml file. 

For the STL Xtext stuff, the grammar has flaws when tested outside the bundle (with a generated ecore model). However, fixing it still causes problems and test failures. 

The ShapeImpl class in the model's generated code should not instantiate it's lists!!! This is done by lazy instantiation and hard coded instantiation breaks some of Xtext's code.

**Comment by SmithRWORNL** [comment]
Addressed by merged pull request #80
