### ISSUE TITLE
Need to add import for STL files

### ISSUE THREAD

**Issue by KasperGam** [eclipse/eavp#84]
The new geometry editor needs to be able to make use of the STLGometryImporter. There should be both implementation to import a file into ICE using Import->Existing File into Item and a menu in the Shape Tree View for an open Geometry Editor.

**Comment by KasperGam** [comment]
Adressed in #83

**Comment by SmithRWORNL** [comment]
This has been merged into next as of 0b1bbd9317bfeddbd5373b6df195473e0c4525e0
