### ISSUE TITLE
Need a way to see or scale small shapes in geometry editor

### ISSUE THREAD

**Issue by KasperGam** [eclipse/eavp#86]
Currently, any shape with small values (all vertices around 1 of each other) cannot be seen in the editor. There needs to be a way of scaling the shape or zooming to be able to handle imports when the file's values are small.

**Comment by KasperGam** [comment]
Added scale property for shapes in #83 , although this is not a perfect solution, as setting the scale changes the model with the current implementation.

**Comment by SmithRWORNL** [comment]
A ScaleDecorator class has been added to control the display size of shapes and it has been merged into next as of commit 0b1bbd9317bfeddbd5373b6df195473e0c4525e0.
