### ISSUE TITLE
Geometry Editor's Transformation Gizmo is clunky- should be toggle-able

### ISSUE THREAD

**Issue by KasperGam** [eclipse/eavp#87]
The gizmo is useful for getting bounds and reference points, but it can look clunky and clog the screen with lines not being drawn with perspective. First, the lines do not have any sort of z buffer, and one is always drawn before the other creating weird visual effects. It also gets in the way when looking at objects close to the origin. It should be toggle-able in the editor to show the user what they're doing but also be there as a guide.

**Comment by SmithRWORNL** [comment]
The lack of a z buffer is intentional, as it is what allows the axis to always be visible through the geometry. Adding to this, it should also be possible to toggle this property and to change the axis size.

**Comment by SmithRWORNL** [comment]
Options to control the display and size of the axes have been added and merged into next as of 0b1bbd9317bfeddbd5373b6df195473e0c4525e0
