### ISSUE TITLE
Performance Analysis on Geometry Editor and Model

### ISSUE THREAD

**Issue by KasperGam** [eclipse/eavp#97]
The new geometry editor and model need analysis on larger scale problems, to see what the RAM usage is per vertex on complex triangular meshes. Try to see where the data usage can be cut down. Perhaps using a cube mesh would be productive, with replication to see what the cost, in RAM, is per triangle or vertex.

**Comment by SmithRWORNL** [comment]
The Geometry Editor will no longer be supported in 0.3
