### ISSUE TITLE
Cannot Change Shape in Union's Properties

### ISSUE THREAD

**Issue by KasperGam** [eclipse/eavp#99]
The shapes in a union take on the properties of the Union automatically, thus not allowing the user to say set only a select number of shapes as solid or transparent on a wireframe union. For opacity and color, the elements of a union should be able to differ from the union as a whole.

**Comment by SmithRWORNL** [comment]
As of commit 1520c0163c1548e615cfa279e8f39aee8cae0bc3 the DisplayOptions for a union can be deactivated, allowing the DisplayOptions of its children to apply unmodified.
